# Generated by Django 5.2.4 on 2025-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("img", models.ImageField(upload_to="product_images/")),
                ("title", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
