# Generated by Django 5.2.4 on 2025-07-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("img", models.ImageField(upload_to="blog_images/")),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
